### ISSUE TITLE
strange syntax coloring

### ISSUE THREAD

**Issue by 0xbs0d** [deadfoxygrandpa/Elm.tmLanguage#107]
Not sure if this is an issue with the plugin but it's happening only with elm files. The syntax colouring is all weird. And this is happening only on OSX. On windows it works fine. And yes, I tried to change themes. 

Any idea?
![screen shot 2016-05-24 at 01 35 38](https://cloud.githubusercontent.com/assets/140889/15487784/38dfeb20-2150-11e6-9278-5a741411bfa2.png)

**Comment by therealmarv** [comment]
I have also a problem regarding this but it is slightly different. Every language in my Sublime Text is colored pretty good except Elm which has nearly no colors here. My color theme is https://github.com/therealmarv/Atom-Dark.tmTheme

![image](https://cloud.githubusercontent.com/assets/1050582/15512782/e0f81670-21e1-11e6-907b-4d7fbc81491b.png)

Are there any special color keys used for Elm?

**Comment by 0xbs0d** [comment]
@therealmarv it depends on the theme. I get either my problem if i use for example monokai, or something like yours if i use spacegrey. and it's only when i work with elm on a mac.

**Comment by tudborg** [comment]
see #101

**Comment by 0xbs0d** [comment]
tnx!
