### ISSUE TITLE
Any plans for Sublime Text 3?

### ISSUE THREAD

**Issue by AdrianoFerrari** [deadfoxygrandpa/Elm.tmLanguage#17]
Hi Alex,

Thanks for creating this package. Any chance of upgrading to Sublime Text 3?

All the best,
Adriano

**Comment by deadfoxygrandpa** [comment]
Yes, eventually. I haven't personally used ST3 yet, but I'd like to support both. Sorry I don't really have a timeframe on this yet.

**Comment by AdrianoFerrari** [comment]
Actually I've been testing this, and I'm not sure how or why, but syntax highlighting works with ST3 already, without installing any packages:

![screenshot - 15-01-03 - 06 43 13 am](https://cloud.githubusercontent.com/assets/323678/5602330/d7160e90-9313-11e4-8a0e-a5c1063c9252.png)

**Comment by elbow-jason** [comment]
Hilariously, on ST3 the autocomplete also brings up available methods for dot notation (which is helpful), but produces the wrong code on completion (which is not helpful).  :P

**Comment by dacjames** [comment]
@AdrianoFerrari 

My fork seems to be working in ST3.  Remove existing plugin, add https://github.com/dacjames/Elm.tmLanguage as a [new repository](https://packagecontrol.io/docs/usage), and install my version.  That should get you going while we wait for a merge upstream.

**Comment by rtfeldman** [comment]
Looks like @dacjames's stuff has been merged...does that mean this issue can be closed?

**Comment by dnalot** [comment]
I have both installed for testing. A lot still doesn't work. I didn't fix it because I'd rather replace it with [Elm Oracle](https://github.com/ElmCast/elm-oracle). I think until there's a specific request it's worth closing.

**Comment by dnalot** [comment]
Planning a quick spike before next release.

**Comment by dnalot** [comment]
Fixed downstream
