### ISSUE TITLE
Crash on selection

### ISSUE THREAD

**Issue by corcillo** [deadfoxygrandpa/Elm.tmLanguage#20]
I just installed the elm language support package via sublime 2 package control.  Sublime kept crashing when I would highlight the elm code in sublime, and I traced it back to the language support plugin code, specifically in Elm Language Support.py's  get_type(view) function.  

I was getting this stack trace on the error:

Traceback (most recent call last):
  File "./sublime_plugin.py", line 200, in on_selection_modified
  File "./sublime_plugin.py", line 154, in run_timed_function
  File "./sublime_plugin.py", line 199, in <lambda>
  File "./Elm Language Support.py", line 346, in on_selection_modified
  File "./Elm Language Support.py", line 312, in get_type
  File "./Elm Language Support.py", line 253, in modules_in_scope
  File "./Elm Language Support.py", line 260, in current_module_name
IndexError: list index out of range

Here is a screenshot of some code that when highlighted caused the crash: 

![screen shot 2015-06-12 at 11 42 04 am](https://cloud.githubusercontent.com/assets/4566203/8137410/17ef00a4-10f8-11e5-9257-5eb64cf23ed7.png)

Any thoughts?  I temporarily stopped the crashes by commenting out the get_type function, which I'm assuming will cause problems in the future.

**Comment by ryanmtaylor** [comment]
This happens to me too!  It makes your (amazing) plugin unusable.

**Comment by corcillo** [comment]
@ryanmtaylor if you comment out what's inside the get_type(view) function in Elm Language Support.py  it will stop crashing.  I've been using it like that for the past few days and it seems to work fine.  It looks like all that function does is find the type signature of the word under the cursor.

**Comment by ryanmtaylor** [comment]
@corcillo totally!  I read your comment and added a comment and `return` statement to the top, although commenting out the method and everywhere that calls it might arguably make more sense...

It works perfectly now.

**Comment by deadfoxygrandpa** [comment]
Hi guys, sorry I haven't commented on this yet. I have a 3 day weekend
starting tonight and I'll totally look into this! Thanks for letting me
know.

**Comment by ryanb** [comment]
I ran into this as well. Is there an update on the status?

**Comment by ryanmtaylor** [comment]
When I got Sublime 3 I didn't need to edit any source code.

**Comment by deadfoxygrandpa** [comment]
Sorry for the delay. I looked into it today and figured out the problem. I'll push an update to fix it.

**Comment by deadfoxygrandpa** [comment]
This should be fixed in the newest version.
