### ISSUE TITLE
Support for 0.15 import syntax

### ISSUE THREAD

**Issue by evancz** [deadfoxygrandpa/Elm.tmLanguage#21]
As of 0.15 the import syntax looks like this:

```elm
import List as L exposing (..)
```

Where the `as` and `exposing` clauses are optional. I found [the relevant code](https://github.com/deadfoxygrandpa/Elm.tmLanguage/blob/master/Syntax%20Highlighting/Elm.tmLanguage#L87) but I have no idea what is going on there.

**Comment by rtfeldman** [comment]
Also relevant: `data` has now become `type alias`

**Comment by dnalot** [comment]
Addressing in syntax rewrite based on [EBNF](https://github.com/Apanatshka/elm-spoofax/blob/master/syntax.ebnf) in `syntax` branch

**Comment by dnalot** [comment]
Fixed in next beta!
