### ISSUE TITLE
Update repo description and URL

### ISSUE THREAD

**Issue by dnalot** [deadfoxygrandpa/Elm.tmLanguage#35]
Link to [Package Control release](https://packagecontrol.io/packages/Elm%20Language%20Support) and add ST3 and features to repo description. It should remain short however because it's listed when installing from Package Control. Possibly "Elm language syntax and tool support for ST2/3".

**Comment by deadfoxygrandpa** [comment]
Do you know if the description supports Markdown, too?

**Comment by deadfoxygrandpa** [comment]
It doesn't really matter. I don't want to rely on it because it shows up as just text in ST anyway
