### ISSUE TITLE
Are type hints for std-lib available?

### ISSUE THREAD

**Issue by Dedoig** [deadfoxygrandpa/Elm.tmLanguage#40]
On OSX ...

If type hints are working, how do I activate / use them?  (Similarly, how do I activate next / previous errors?)

If there is some file / doc / etc. I should look at for this kind of stuff, pointer appreciated. If this question is not appropriate for an issue, apologies and please point me to a better place.

Loving the plug-in!!

**Comment by dnalot** [comment]
Have you read the [README](https://github.com/deadfoxygrandpa/Elm.tmLanguage/blob/master/README.md#features) already about navigating errors? I'm personally improving this next release with the help and groundwork of @bbugh. Only errors including a file name and line number work. We are slightly constrained by the underlying CLI. Type hinting was neglected but @deadfoxygrandpa is finishing a complete refactor with the help and groundwork @ajhager. I plan to release a first beta this weekend if you're interested in testing. Please open additional issues with as many specifics as possible if you identify that doesn't work as expected or could work friendlier. I'll attempt to address them in our feature release if within scope!

**Comment by dnalot** [comment]
Closing in favor of #42.
