### ISSUE TITLE
Error Navigation not working on OSX

### ISSUE THREAD

**Issue by Dedoig** [deadfoxygrandpa/Elm.tmLanguage#42]
The README describes a key-combo for error navigation, and assuming Super=Cmd on OSX, it did not work for me when compiler errors included filename + line number. I tried some other key combos after Cmd-F4 and Cmd-Sh-F4, without luck, then looked in Preferences / Package Settings / Elm Language Support to check key shortcut settings without luck. (Hopefully this is not some dumb operator error on my part.)

**Comment by dnalot** [comment]
Did you run the Build command? Were there any results in the Output Panel?

**Comment by Dedoig** [comment]
Yes. I run either Build (Cmd-B) or Run (Cmd-Sh-B), get a list of errors in the output panel, and then try to navigate to errors.

**Comment by dnalot** [comment]
Could you paste the errors into the issue to check the regex? The console output might help too (<kbd>Super+`</kbd>). Make sure to close and reopen Sublime first.

**Comment by Dedoig** [comment]
Here is one error output cut/paste from Sublime after a Cmd-B Build:
```
==== error in Cpu.elm:111:36: ====
Cannot find variable `disabled`
Maybe you want one of the following?
    Html.Attributes.disabled
----
[Finished in 0.2s with exit code 1]
```

I wonder if this is more a key binding problem I am having?

**Comment by dnalot** [comment]
Send me a calendar invite for a Hangout sometime. The error looks good. Any problems in the Console?

**Comment by dnalot** [comment]
Closing pending feedback.

**Comment by Dedoig** [comment]
Aargh. It _was_ just a keybinding problem. I suddenly noticed extra screenshots appearing on my desktop today. Investigated, and my System Prefs / Keyboard Shortcuts was using F4 for screenshots. Got rid of it, and Sublime / Elm navigation is working. Yay!

Btw, now with an Elm Dash docset available, the Sublime / Elm plugin / docs ecosystem is pretty amazing, just ^h to browse docs. https://groups.google.com/forum/#!searchin/elm-discuss/peter$20docset/elm-discuss/k5E7x3McYwM/btHGxwa3CgAJ
