### ISSUE TITLE
repl silently fails if node.js is not present

### ISSUE THREAD

**Issue by JoeyEremondi** [deadfoxygrandpa/Elm.tmLanguage#45]
Not a huge issue, but if you don't have node.js installed, opening the Elm SublimeREPL just silently does nothing. It would be nice if an error message were displayed. (Not sure how possible this is).

**Comment by dnalot** [comment]
I suspect there's nothing to be done. Our command is a standardized proxy to another package which itself primarily proxies the CLI I/O. What does `elm repl` do?

**Comment by dnalot** [comment]
Closing as upstream issue.
