### ISSUE TITLE
Make build warnings optional

### ISSUE THREAD

**Issue by nikita-volkov** [deadfoxygrandpa/Elm.tmLanguage#50]
Evan's dismissed this as a Sublime Plugin issue:
https://github.com/elm-lang/elm-make/issues/58

**Comment by deadfoxygrandpa** [comment]
OK, understood.

**Comment by deadfoxygrandpa** [comment]
@nikita-volkov Would you prefer to have optional build warnings globally, via a package setting, or additional build command variants with warnings enabled or disabled?

**Comment by nikita-volkov** [comment]
Having a global option would be useful IMO.

**Comment by deadfoxygrandpa** [comment]
Well, I've added two new build command variants to ignore warnings. I might change this to a global option later, but try it out and let me know if it works.
