### ISSUE TITLE
I don't understand the installation instructions

### ISSUE THREAD

**Issue by cabalamat** [deadfoxygrandpa/Elm.tmLanguage#52]
In particular I don't know what the 2nd line means:

2. Run Package Control: Install Package in the Command Palette (Super+Shift+P)

(I assume this is an instruction within Sublime Text, however I am just beginning to use that)

Would it be possible to make this instruction more explicit?

**Comment by dnalot** [comment]
The command palette (its shortcut is listed above) is the most basic way to use Sublime Text and now shared with most popular editor including Atom, VS Code, and JetBrains products. I assume you figured it out?
