### ISSUE TITLE
SublimeREPL integration doesn't work

### ISSUE THREAD

**Issue by thisredone** [deadfoxygrandpa/Elm.tmLanguage#53]
It just doesn't do anything; console is empty.
Same thing on Windows 8.1 and Ubuntu 15.10

**Comment by deadfoxygrandpa** [comment]
Can you try from the File menu instead of through the Command Palette? (Tools > SublimeREPL > Elm). Does that work?

**Comment by thisredone** [comment]
Yes, it does work this way :)

**Comment by deadfoxygrandpa** [comment]
OK, then I think I know the problem and how to fix it.

**Comment by deadfoxygrandpa** [comment]
This should be fixed. The update should be live if you've installed through Package Control. If you upgrade and it's not fixed, please reopen this and let me know.
