### ISSUE TITLE
Doesn't work after update (Windows)

### ISSUE THREAD

**Issue by thisredone** [deadfoxygrandpa/Elm.tmLanguage#55]
I've upgraded but now there is no syntax highlighting and after running SublimeREPL: Elm command I get an Error saying `Error loading syntax file "Packages/Elm Language Support/Syntaxes/Elm.tm.Language": Expected element key`. The REPL does work though after that but also without the syntax highlighting.

**Comment by deadfoxygrandpa** [comment]
Can you check your Packages directory and see if there is a folder named Elm Language Support? If not, is there a Elm Language Support sublime-package inside the Installed Packages directory?

**Comment by coreytrampe** [comment]
Same issue on OSX 10.11.2.
No Elm Language Support package in Installed Packages.

Reinstalling doesn't work.

**Comment by thisredone** [comment]
There is no Elm Language Support in the packages folder (Browse Packages) but I think there never was.
There is however `Elm Language Support.sublime-package` file in the Installed Packages folder.

**Comment by mdtusz** [comment]
Same issue here with st3.

There's no `Elm Language Support` directory in the `Packages` directory, but there's a `Elm Language Support.sublime-package` in `Installed Packages` and an `Elm Language Support` directory in `Cache`.

**Comment by deadfoxygrandpa** [comment]
OK, I just pushed a new update that's live on Package Control. If you guys upgrade your Elm Language Support package now, are you still seeing this issue? I think it _should_ be fixed.

**Comment by eniac314** [comment]
I have an Elm Language Support inside .config/sublime-text-3/Packages/Elm Language Support (linux mint 17), and the latest upgrade I think, but syntax highlighting is not working.

**Comment by deadfoxygrandpa** [comment]
Oops, it looks like I screwed up a merge into the master branch and broke the syntax highlighting file. I'll fix it asap.

**Comment by deadfoxygrandpa** [comment]
OK, sorry about all this. I think this should finally be fixed now.

**Comment by eniac314** [comment]
Seems to be working now, thank you.

**Comment by deadfoxygrandpa** [comment]
If anyone else is still having this problem, please reopen this issue.
