### ISSUE TITLE
(beta) autocomplete shortens the result after enter

### ISSUE THREAD

**Issue by thisredone** [deadfoxygrandpa/Elm.tmLanguage#65]
I have `import Task exposing (Task)` at the top of the file and when I type `Task.succ` and press enter it autocompletes to `succeed` instead of `Task.succeed`

**Comment by deadfoxygrandpa** [comment]
Thanks for letting me know. I'll look into why it's happening

**Comment by deadfoxygrandpa** [comment]
This issue should be fixed now. Let me know if you find any more problems.

**Comment by thisredone** [comment]
Amazing :) :+1:
