### ISSUE TITLE
Syntax error in Elm Language Support - Error trying to parse settings: Trailing comma before closing bracket

### ISSUE THREAD

**Issue by gijsterhorst** [deadfoxygrandpa/Elm.tmLanguage#78]
There is a comma just before the closing } in the Elm Language Support  file.

This causes Sublime Test 2 to run into a parsing error: Error trying to parse settings: Trailing comma before closing bracket ...

It can be easily fixed by deleting the final comma.

**Comment by deadfoxygrandpa** [comment]
Oh, OK. Thanks for letting me know. It will be fixed ASAP.

**Comment by deadfoxygrandpa** [comment]
This is fixed in the latest beta, and will be in the next release.
