### ISSUE TITLE
error parsing settings on launch

### ISSUE THREAD

**Issue by fergusmeiklejohn** [deadfoxygrandpa/Elm.tmLanguage#90]
I'm getting this error every time I launch Sublime:

"Error trying to parse settings: Unexpected trailing characters in Packages/User/Elm Language Support.sublime-settings:1:21"

I've removed and reinstalled the Elm language package but it makes no difference and I also had this problem before the latest version was released.

This Elm Language Support.sublime-settings file is exactly as it is when installed I haven't changed it at all

**Comment by deadfoxygrandpa** [comment]
Can you post the contents of your Packages/User/Elm Language
Support.sublime-settings file? It looks like you have something incorrect
inside it, maybe an invalid trailing comma or something?

**Comment by fergusmeiklejohn** [comment]
thanks very much! It was just:

"elm_format_on_save": true

But because this is now in Settings-Default anyway I've just deleted it from my Settings-User and the error message is gone :-)

**Comment by deadfoxygrandpa** [comment]
Oh, OK. For reference, the settings files are supposed to be valid JSON, so if you only have one setting you would need to enclose it in { } brackets.

**Comment by fergusmeiklejohn** [comment]
ah right!  I just copied and pasted it from the ReadMe ><
Well I've learned a good lesson then..

thanks for your help

**Comment by deadfoxygrandpa** [comment]
I guess I should make that more clear.
